# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 648391dc5e681983a9cbc8ca14155c43f23c06f1a925f2fc1807622c1933b5e926d0e1f6a8edda812be4e983da4f968960e21d5ef58a8a44fbf52f7335f25178

test:
  secret_key_base: e825fd5bb9699efd71c2821c2a7e230766bbfdbfc95ee47f4dc34eb926c36fb83d9413618581e6d69976ecdb4abd700a8386b7667334c05e0914e78e70cd0a87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
